public class DataSource {

    public static String[] nombreEquipos = {
                                                "Fc Barcelona",
                                                "Real Madrid",
                                                "Atletico de Madrid",
                                                "Sevilla",
                                                "Betis",
                                                "Valencia",
                                                "Villareal",
                                                "Rayo Vallecano",
                                                "Español",
                                                "Girona",
                                                "Real Sociedad",
                                                "Athletic Club",
                                                "FC Osasuna",
                                                "CD Mallorca",
                                                "Celta de Vigo",
                                                "Almeria",
                                                "Cadíz",
                                                "Valladolid",
                                                "Getafe",
                                                "Elche"
    };
    public static String[] nombreEstadios = {
                                                "Spotify Camp Nou",
                                                "Santiago Bernabeu",
                                                "Civitas Metropolitano",
                                                "Sanchez Pijuan",
                                                "Benito Villamarin",
                                                "Mestalla",
                                                "La Ceramica",
                                                "Vallecas",
                                                "Cornellat",
                                                "Montilivi",
                                                "Reale Arena(Anoeta)",
                                                "San Mames",
                                                "El Sadar",
                                                "Son Moix",
                                                "Abanca Valaidos",
                                                "Juegos Mediterraneos",
                                                "Nuevo Mirandilla",
                                                "Jose Zorrilla",
                                                "Alfonso Perez",
                                                "Manuel Martinez Velero"
    };
    public static String[] nombreAficiones = {
                                                "Culés",
                                                "Merengues",
                                                "Colchoneros",
                                                "Palanganas",
                                                "Beticos",
                                                "Ché",
                                                "groguets",
                                                "Franjirojos",
                                                "Pericos",
                                                "Albirrojos",
                                                "txuri-urdin",
                                                "Leones",
                                                "rojillos",
                                                "Bermellon",
                                                "Olivicos",
                                                "Indalicos",
                                                "Submarino Amarillo",
                                                "vallisoletanos",
                                                "Azulones",
                                                "Ilicitano"
    };
    public static String[] nombreJugadores = {
                                                "Marc-André",
                                                "Thibaut",
                                                "Jan",
                                                "Yassine",
                                                "Claudio",
                                                "Giorgi",
                                                "Filip",
                                                "Stole",
                                                "Joan",
                                                "Paulo",
                                                "Alejandro",
                                                "Unai",
                                                "Sergio",
                                                "Predrag",
                                                "Agustin",
                                                "Fernando",
                                                "Jeremias",
                                                "Jordi",
                                                "David",
                                                "Edgar"
    };
    public static String[] apellidoJugadores = {
                                                "Ter Stegen",
                                                "Courtois",
                                                "Oblak",
                                                "Bono",
                                                "Bravo",
                                                "Mamardashvili",
                                                "Jorgensen",
                                                "Dimitrievski",
                                                "Garcia Pons",
                                                "Gazzaniga",
                                                "Remiro Gargallo",
                                                "Simon Mendibil",
                                                "Herrera",
                                                "Rajkovic",
                                                "Marchesin",
                                                "Martinez Rubio",
                                                "Connan Ledesma",
                                                "Masip",
                                                "Soria Solis",
                                                "Badia"
    };

    public static int[] idJugadores = {
                                                0,
                                                1,
                                                2,
                                                3,
                                                4,
                                                5,
                                                6,
                                                7,
                                                8,
                                                9,
                                                10,
                                                11,
                                                12,
                                                13,
                                                14,
                                                15,
                                                16,
                                                17,
                                                18,
                                                19

    };
    public static int[] edad = {
                                                31,
                                                31,
                                                30,
                                                32,
                                                40,
                                                22,
                                                21,
                                                29,
                                                22,
                                                31,
                                                28,
                                                25,
                                                29,
                                                27,
                                                35,
                                                32,
                                                30,
                                                34,
                                                30,
                                                31
    };
    public static int[] numero = {
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1
    };
    public static int[] goles = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
    public static int[] asistencias = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
    public static int[] tarjetas_Amarillas = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
    public static int[] tarjetas_Rojas = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
public static String[] nombreArbitro = {
                                            "Juan Luis Pulido Santana",
                                            "Isidro Díaz de Mera Escuderos",
                                            "Javier Alberola Rojas",
                                            "Ricardo de Burgos Bongoetxea",
                                            "Carlos del Cerro Grande",
                                            "Jorge Figueroa Vazquez",
                                            "Jesus Gil Manzano",
                                            "Pablo Gonzalez Fuertes",
                                            "Alejandro Herandez Hernandez",
                                            "Javier Iglesias Villanueva",
                                            "Juan Martinez Munuera",
                                            "Antonio Mateu Lahoz",
                                            "Mario Melero Lopez",
                                            "Jose Luis Munuera Montero",
                                            "Alejandro Muñiz Ruiz",
                                            "Miguel Angel Ortiz Arias",
                                            "Valentin Pizarro Gomez",
                                            "Jose Maria Sanchez Martinez",
                                            "Cesar Soto Grado",
                                            "Guillermo Cuadra Fernandez"
    };
public static int[] sueldo = {
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500,
                                3500
    };
public static String[] nacionalidad = {
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
                                        "España",
    };
public static int[] nArbitro = {
                                    0,
                                    1,
                                    2,
                                    3,
                                    4,
                                    5,
                                    6,
                                    7,
                                    8,
                                    9,
                                    10,
                                    11,
                                    12,
                                    13,
                                    14,
                                    15,
                                    16,
                                    17,
                                    18,
                                    19
    };
public static int[] amonestaciones = {
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0
    };
public static int[] expulsiones = {
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0,
                                        0
    };
public static String[] n_jornada = {
                                        "1a",
                                        "2a",
                                        "3a",
                                        "4a",
                                        "5a",
                                        "6a",
                                        "7a",
                                        "8a",
                                        "9a",
                                        "10a",
                                        "11a",
                                        "12a",
                                        "13a",
                                        "14a",
                                        "15a",
                                        "16a",
                                        "17a",
                                        "18a",
                                        "19a"
    };
public static String[] equipos_participantes = {
                                                    "FCB-BET",
                                                    "FCB-SEV",
                                                    "FCB-ESP",
                                                    "FCB-RSC",
                                                    "FCB-VAL",
                                                    "FCB-VIL",
                                                    "FCB-GET",
                                                    "FCB-ATH",
                                                    "FCB-ATL",
                                                    "FCB-RMA",
                                                    "FCB-OSA",
                                                    "FCB-VAD",
                                                    "FCB-ALM",
                                                    "FCB-CAD",
                                                    "FCB-RAY",
                                                    "FCB-GIR",
                                                    "FCB-MRC",
                                                    "FCB-CLT",
                                                    "FCB-ELC",
    };
public static int[] fecha = {
                                12 / 8,
                                19 / 8,
                                26 / 8,
                                2 / 9,
                                9 / 9,
                                16 / 9,
                                30 / 9,
                                7 / 10,
                                14 / 10,
                                18 / 10,
                                22 / 10,
                                28 / 10,
                                4 / 11,
                                8 / 11,
                                29 / 11,
                                6 / 1,
                                13 / 1,
                                20 / 1,
                                27 / 1
    };
public static int[] resultado = {
                                    1 - 0,
                                    2 - 0,
                                    4 - 0,
                                    1 - 0,
                                    3 - 1,
                                    5 - 2,
                                    3 - 0,
                                    2 - 1,
                                    1 - 1,
                                    3 - 0,
                                    1 - 0,
                                    4 - 0,
                                    2 - 1,
                                    1 - 1,
                                    2 - 0,
                                    1 - 2,
                                    1 - 0,
                                    3 - 0
    };
public static String[] incidencias = {
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna",
                                        "Ninguna"
    };
public static String[] revisiones = {
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK",
                                        "Todo OK"
    };
}