public class DataSource {

    public static String[] nombreEquipos = {
                                                "Fc Barcelona",
                                                "Real Madrid",
                                                "Atletico de Madrid",
                                                "Sevilla",
                                                "Betis",
                                                "Valencia",
                                                "Villareal",
                                                "Rayo Vallecano",
                                                "Español",
                                                "Girona",
                                                "Real Sociedad",
                                                "Athletic Club",
                                                "FC Osasuna",
                                                "CD Mallorca",
                                                "Celta de Vigo",
                                                "Almeria",
                                                "Cadíz",
                                                "Valladolid",
                                                "Getafe",
                                                "Elche"
    };
    public static String[] nombreEstadios = {
                                                "Spotify Camp Nou",
                                                "Santiago Bernabeu",
                                                "Civitas Metropolitano",
                                                "Sanchez Pijuan",
                                                "Benito Villamarin",
                                                "Mestalla",
                                                "La Ceramica",
                                                "Vallecas",
                                                "Cornellat",
                                                "Montilivi",
                                                "Reale Arena(Anoeta)",
                                                "San Mames",
                                                "El Sadar",
                                                "Son Moix",
                                                "Abanca Valaidos",
                                                "Juegos Mediterraneos",
                                                "Nuevo Mirandilla",
                                                "Jose Zorrilla",
                                                "Alfonso Perez",
                                                "Manuel Martinez Velero"
    };
    public static String[] nombreAficiones = {
                                                "Culés",
                                                "Merengues",
                                                "Colchoneros",
                                                "Palanganas",
                                                "Beticos",
                                                "Ché",
                                                "groguets",
                                                "Franjirojos",
                                                "Pericos",
                                                "Albirrojos",
                                                "txuri-urdin",
                                                "Leones",
                                                "rojillos",
                                                "Bermellon",
                                                "Olivicos",
                                                "Indalicos",
                                                "Submarino Amarillo",
                                                "vallisoletanos",
                                                "Azulones",
                                                "Ilicitano"
    };
    public static String[] nombreJugadores = {
                                                "Marc-André",
                                                "Thibaut",
                                                "Jan",
                                                "Yassine",
                                                "Claudio",
                                                "Giorgi",
                                                "Filip",
                                                "Stole",
                                                "Joan",
                                                "Paulo",
                                                "Alejandro",
                                                "Unai",
                                                "Sergio",
                                                "Predrag",
                                                "Agustin",
                                                "Fernando",
                                                "Jeremias",
                                                "Jordi",
                                                "David",
                                                "Edgar"
    };
    public static String[] apellidoJugadores = {
                                                "Ter Stegen",
                                                "Courtois",
                                                "Oblak",
                                                "Bono",
                                                "Bravo",
                                                "Mamardashvili",
                                                "Jorgensen",
                                                "Dimitrievski",
                                                "Garcia Pons",
                                                "Gazzaniga",
                                                "Remiro Gargallo",
                                                "Simon Mendibil",
                                                "Herrera",
                                                "Rajkovic",
                                                "Marchesin",
                                                "Martinez Rubio",
                                                "Connan Ledesma",
                                                "Masip",
                                                "Soria Solis",
                                                "Badia"
    };

    public static int[] idJugadores = {
                                                0,
                                                1,
                                                2,
                                                3,
                                                4,
                                                5,
                                                6,
                                                7,
                                                8,
                                                9,
                                                10,
                                                11,
                                                12,
                                                13,
                                                14,
                                                15,
                                                16,
                                                17,
                                                18,
                                                19

    };
    public static int[] edad = {
                                                31,
                                                31,
                                                30,
                                                32,
                                                40,
                                                22,
                                                21,
                                                29,
                                                22,
                                                31,
                                                28,
                                                25,
                                                29,
                                                27,
                                                35,
                                                32,
                                                30,
                                                34,
                                                30,
                                                31
    };
    public static int[] numero = {
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1
    };
    public static int[] goles = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
    public static int[] asistencias = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
    public static int[] tarjetas_Amarillas = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
    public static int[] tarjetas_Rojas = {
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0,
                                                0
    };
}