import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        Liga liga1 = new Liga("Liga BBVA");
        Equipo equipo1 = new Equipo("Fc Barcelona","Spotify Camp Nou", 0, "Culés");
        Equipo equipo2 = new Equipo("Real Madrid", "Santiago Bernabeu", 0, "Merengues");
        Equipo equipo3 = new Equipo("Atletico de Madrid", "Civitas Metropolitano", 0, "Colchoneros");
        Equipo equipo4 = new Equipo("Sevilla", "Sanchez Pijuan", 0, "Palanganas");
        Equipo equipo5 = new Equipo("Betis", "Benito Villamarin", 0, "Beticos");
        Equipo equipo6 = new Equipo("Valencia", "Mestalla", 0, "Ché");
        Equipo equipo7 = new Equipo("Villareal", "Ceramica", 0, "groguets");
        Equipo equipo8 = new Equipo("Rayo Vallecano", "Vallecas", 0, "Franjirojos");
        Equipo equipo9 = new Equipo("Español", "Cornellat", 0, "Pericos");
        Equipo equipo10= new Equipo("Girona", "Montilivi", 0, "Albirrojos");
        Equipo equipo11= new Equipo("Real Sociedad", "Reale Arena(Anoeta)", 0, "txuri-urdin");
        Equipo equipo12= new Equipo("Athletic Club", "San Mames", 0, "Leones");
        Equipo equipo13= new Equipo("FC Osasuna", "El Sadar", 0, "rojillos");
        Equipo equipo14= new Equipo("Mallorca", "Son Moix", 0, "Bermellon");
        Equipo equipo15= new Equipo("Celta de Vigo", "Abanca Valaidos", 0, "Olivicos");
        Equipo equipo16= new Equipo("Almeria", "Juegos Mediterraneos", 0, "Indalicos");
        Equipo equipo17= new Equipo("Cadíz", "Nuevo Mirandilla", 0, "Submarino Amarillo");
        Equipo equipo18= new Equipo("Valladolid", "Jose Zorrilla", 0, "vallisoletanos");
        Equipo equipo19= new Equipo("Getafe ", "Alfonso Perez", 0, "Azulones");
        Equipo equipo20= new Equipo("Elche", "Manuel Martinez Velero", 0, "Ilicitano");
        Jugador portero1 = new Jugador("",29,1,0,0,0,0);
        Jugador portero2 = new Jugador("",29,1,0,0,0,0);
        Jugador portero3 = new Jugador("",29,1,0,0,0,0);
        Jugador portero4 = new Jugador("",29,1,0,0,0,0);
        Jugador portero5 = new Jugador("",29,1,0,0,0,0);
        Jugador portero6 = new Jugador("",29,1,0,0,0,0);
        Jugador portero7 = new Jugador("",29,1,0,0,0,0);
        Jugador portero8 = new Jugador("",29,1,0,0,0,0);
        Jugador portero9 = new Jugador("",29,1,0,0,0,0);
        Jugador portero10 = new Jugador("",29,1,0,0,0,0);
        Jugador portero11 = new Jugador("",29,1,0,0,0,0);
        Jugador portero12 = new Jugador("",29,1,0,0,0,0);
        Jugador portero13 = new Jugador("",29,1,0,0,0,0);
        Jugador portero14 = new Jugador("",29,1,0,0,0,0);
        Jugador portero15 = new Jugador("",29,1,0,0,0,0);
        Jugador portero16 = new Jugador("",29,1,0,0,0,0);
        Jugador portero17 = new Jugador("",29,1,0,0,0,0);
        Jugador portero18 = new Jugador("",29,1,0,0,0,0);
        Jugador portero19 = new Jugador("",29,1,0,0,0,0);
        Jugador portero20 = new Jugador("",29,1,0,0,0,0);
        Arbitro arbitro1 = new Arbitro("",5000,"Española", 1,0,0);
        Arbitro arbitro2 = new Arbitro("",5000,"Española", 2,0,0);
        Arbitro arbitro3 = new Arbitro("",5000,"Española", 3,0,0);
        Arbitro arbitro4 = new Arbitro("",5000,"Española", 4,0,0);
        Arbitro arbitro5 = new Arbitro("",5000,"Española", 5,0,0);
        Arbitro arbitro6 = new Arbitro("",5000,"Española", 6,0,0);
        Arbitro arbitro7 = new Arbitro("",5000,"Española", 7,0,0);
        Arbitro arbitro8 = new Arbitro("",5000,"Española", 8,0,0);
        Arbitro arbitro9 = new Arbitro("",5000,"Española", 9,0,0);
        Arbitro arbitro10 = new Arbitro("",5000,"Española", 10,0,0);
        Arbitro arbitro11 = new Arbitro("",5000,"Española", 11,0,0);
        Arbitro arbitro12 = new Arbitro("",5000,"Española", 12,0,0);
        Arbitro arbitro13 = new Arbitro("",5000,"Española", 13,0,0);
        Arbitro arbitro14 = new Arbitro("",5000,"Española", 14,0,0);
        Arbitro arbitro15 = new Arbitro("",5000,"Española", 15,0,0);
        Arbitro arbitro16 = new Arbitro("",5000,"Española", 16,0,0);
        Arbitro arbitro17 = new Arbitro("",5000,"Española", 17,0,0);
        Arbitro arbitro18 = new Arbitro("",5000,"Española", 18,0,0);
        Arbitro arbitro19 = new Arbitro("",5000,"Española", 19,0,0);
        Arbitro arbitro20 = new Arbitro("",5000,"Española", 20,0,0);
        Jornada jornada1 = new Jornada(1,1-0,"ninguna","Todo OK");
        Jornada jornada2 = new Jornada(2,1-0,"ninguna","Todo OK");
        Jornada jornada3 = new Jornada(3,1-0,"ninguna","Todo OK");
        Jornada jornada4 = new Jornada(4,1-0,"ninguna","Todo OK");
        Jornada jornada5 = new Jornada(5,1-0,"ninguna","Todo OK");
        Jornada jornada6 = new Jornada(6,1-0,"ninguna","Todo OK");
        Jornada jornada7 = new Jornada(7,1-0,"ninguna","Todo OK");
        Jornada jornada8 = new Jornada(8,1-0,"ninguna","Todo OK");
        Jornada jornada9 = new Jornada(9,1-0,"ninguna","Todo OK");
        Jornada jornada10 = new Jornada(10,1-0,"ninguna","Todo OK");
        Jornada jornada11 = new Jornada(11,1-0,"ninguna","Todo OK");
        Jornada jornada12 = new Jornada(12,1-0,"ninguna","Todo OK");
        Jornada jornada13 = new Jornada(13,1-0,"ninguna","Todo OK");
        Jornada jornada14 = new Jornada(14,1-0,"ninguna","Todo OK");
        Jornada jornada15 = new Jornada(15,1-0,"ninguna","Todo OK");
        Jornada jornada16 = new Jornada(16,1-0,"ninguna","Todo OK");
        Jornada jornada17 = new Jornada(17,1-0,"ninguna","Todo OK");
        Jornada jornada18 = new Jornada(18,1-0,"ninguna","Todo OK");
        Jornada jornada19 = new Jornada(19,1-0,"ninguna","Todo OK");
        Jornada jornada20 = new Jornada(20,1-0,"ninguna","Todo OK");
        liga1.getEquipos().add(equipo1);
        liga1.getEquipos().add(equipo2);
        liga1.getEquipos().add(equipo3);
        liga1.getEquipos().add(equipo4);
        liga1.getEquipos().add(equipo5);
        liga1.getEquipos().add(equipo6);
        liga1.getEquipos().add(equipo7);
        liga1.getEquipos().add(equipo8);
        liga1.getEquipos().add(equipo9);
        liga1.getEquipos().add(equipo10);
        liga1.getEquipos().add(equipo11);
        liga1.getEquipos().add(equipo12);
        liga1.getEquipos().add(equipo13);
        liga1.getEquipos().add(equipo14);
        liga1.getEquipos().add(equipo15);
        liga1.getEquipos().add(equipo16);
        liga1.getEquipos().add(equipo17);
        liga1.getEquipos().add(equipo18);
        liga1.getEquipos().add(equipo19);
        liga1.getEquipos().add(equipo20);
        equipo1.getJugadores().add(portero1);
        equipo2.getJugadores().add(portero2);
        equipo3.getJugadores().add(portero3);
        equipo4.getJugadores().add(portero4);
        equipo5.getJugadores().add(portero5);
        equipo6.getJugadores().add(portero6);
        equipo7.getJugadores().add(portero7);
        equipo8.getJugadores().add(portero8);
        equipo9.getJugadores().add(portero9);
        equipo10.getJugadores().add(portero10);
        equipo11.getJugadores().add(portero11);
        equipo12.getJugadores().add(portero12);
        equipo13.getJugadores().add(portero13);
        equipo14.getJugadores().add(portero14);
        equipo15.getJugadores().add(portero15);
        equipo16.getJugadores().add(portero16);
        equipo17.getJugadores().add(portero17);
        equipo18.getJugadores().add(portero18);
        equipo19.getJugadores().add(portero19);
        equipo20.getJugadores().add(portero20);
        jornada1.getArbitros().add(arbitro1);
        jornada2.getArbitros().add(arbitro2);
        jornada3.getArbitros().add(arbitro3);
        jornada4.getArbitros().add(arbitro4);
        jornada5.getArbitros().add(arbitro5);
        jornada6.getArbitros().add(arbitro6);
        jornada7.getArbitros().add(arbitro7);
        jornada8.getArbitros().add(arbitro8);
        jornada9.getArbitros().add(arbitro9);
        jornada10.getArbitros().add(arbitro10);
        jornada11.getArbitros().add(arbitro11);
        jornada12.getArbitros().add(arbitro12);
        jornada13.getArbitros().add(arbitro13);
        jornada14.getArbitros().add(arbitro14);
        jornada15.getArbitros().add(arbitro15);
        jornada16.getArbitros().add(arbitro16);
        jornada17.getArbitros().add(arbitro17);
        jornada18.getArbitros().add(arbitro18);
        jornada19.getArbitros().add(arbitro19);
        jornada20.getArbitros().add(arbitro20);
        System.out.println(liga1);
    }
}
