import java.util.ArrayList;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        Fifa fifa = new Fifa("Zeferin", 20);
        Rfef rfef = new Rfef("Luis Manuel Rubiales", "LIGA BBVA, Copa del Rey", "Real Madrid", 1000000000);
        Liga liga1 = new Liga("Liga BBVA", "España", 1000000000);
        System.out.println(liga1);
        Equipo equipo1 = new Equipo("Fc Barcelona", "Spotify Camp Nou", 0, "Culés");
        Equipo equipo2 = new Equipo("Real Madrid", "Santiago Bernabeu", 0, "Merengues");
        Equipo equipo3 = new Equipo("Atletico de Madrid", "Civitas Metropolitano", 0, "Colchoneros");
        Equipo equipo4 = new Equipo("Sevilla", "Sanchez Pijuan", 0, "Palanganas");
        Equipo equipo5 = new Equipo("Betis", "Benito Villamarin", 0, "Beticos");
        Equipo equipo6 = new Equipo("Valencia", "Mestalla", 0, "Ché");
        Equipo equipo7 = new Equipo("Villareal", "Ceramica", 0, "groguets");
        Equipo equipo8 = new Equipo("Rayo Vallecano", "Vallecas", 0, "Franjirojos");
        Equipo equipo9 = new Equipo("Español", "Cornellat", 0, "Pericos");
        Equipo equipo10 = new Equipo("Girona", "Montilivi", 0, "Albirrojos");
        Equipo equipo11 = new Equipo("Real Sociedad", "Reale Arena(Anoeta)", 0, "txuri-urdin");
        Equipo equipo12 = new Equipo("Athletic Club", "San Mames", 0, "Leones");
        Equipo equipo13 = new Equipo("FC Osasuna", "El Sadar", 0, "rojillos");
        Equipo equipo14 = new Equipo("Mallorca", "Son Moix", 0, "Bermellon");
        Equipo equipo15 = new Equipo("Celta de Vigo", "Abanca Valaidos", 0, "Olivicos");
        Equipo equipo16 = new Equipo("Almeria", "Juegos Mediterraneos", 0, "Indalicos");
        Equipo equipo17 = new Equipo("Cadíz", "Nuevo Mirandilla", 0, "Submarino Amarillo");
        Equipo equipo18 = new Equipo("Valladolid", "Jose Zorrilla", 0, "vallisoletanos");
        Equipo equipo19 = new Equipo("Getafe ", "Alfonso Perez", 0, "Azulones");
        Equipo equipo20 = new Equipo("Elche", "Manuel Martinez Velero", 0, "Ilicitano");
        Jugador portero1 = new Jugador("Marc-André", "Ter Stegen", 1, 31, 1, 0, 0, 0, 0);
        Jugador portero2 = new Jugador("Thibaut", "Courtois", 2, 31, 1, 0, 0, 0, 0);
        Jugador portero3 = new Jugador("Jan", "Oblak", 3, 30, 1, 0, 0, 0, 0);
        Jugador portero4 = new Jugador("Yassine", "Bono", 4, 32, 1, 0, 0, 0, 0);
        Jugador portero5 = new Jugador("Claudio", "Bravo", 5, 40, 1, 0, 0, 0, 0);
        Jugador portero6 = new Jugador("Giorgi", "Mamardashvili", 6, 22, 1, 0, 0, 0, 0);
        Jugador portero7 = new Jugador("Filip", "Jorgensen", 7, 21, 1, 0, 0, 0, 0);
        Jugador portero8 = new Jugador("Stole", "Dimitrievski", 8, 29, 1, 0, 0, 0, 0);
        Jugador portero9 = new Jugador("Joan", "Garcia Pons", 9, 22, 1, 0, 0, 0, 0);
        Jugador portero10 = new Jugador("Paulo", "Gazzaniga", 10, 31, 1, 0, 0, 0, 0);
        Jugador portero11 = new Jugador("Alejandro", "Remiro Gargallo", 11, 28, 1, 0, 0, 0, 0);
        Jugador portero12 = new Jugador("Unai", "Simon Mendibil", 12, 25, 1, 0, 0, 0, 0);
        Jugador portero13 = new Jugador("Sergio", "Herrera", 13, 29, 1, 0, 0, 0, 0);
        Jugador portero14 = new Jugador("Predrag", "Rajkovic", 14, 27, 1, 0, 0, 0, 0);
        Jugador portero15 = new Jugador("Agustin", "Marchesin", 15, 35, 1, 0, 0, 0, 0);
        Jugador portero16 = new Jugador("Fernando", "Martinez Rubio", 16, 32, 1, 0, 0, 0, 0);
        Jugador portero17 = new Jugador("Jeremias", "Connan Ledesma", 17, 30, 1, 0, 0, 0, 0);
        Jugador portero18 = new Jugador("Jordi", "Masip", 18, 34, 1, 0, 0, 0, 0);
        Jugador portero19 = new Jugador("David", "Soria Solis", 19, 30, 1, 0, 0, 0, 0);
        Jugador portero20 = new Jugador("Edgar", "Badia", 20, 31, 1, 0, 0, 0, 0);
        Arbitro arbitro1 = new Arbitro("Juan Luis Pulido Santana", 5000, "Española", 1, 0, 0);
        Arbitro arbitro2 = new Arbitro("Isidro Díaz de Mera Escuderos", 5000, "Española", 2, 0, 0);
        Arbitro arbitro3 = new Arbitro("Javier Alberola Rojas", 5000, "Española", 3, 0, 0);
        Arbitro arbitro4 = new Arbitro("Ricardo de Burgos Bongoetxea", 5000, "Española", 4, 0, 0);
        Arbitro arbitro5 = new Arbitro("Carlos del Cerro Grande", 5000, "Española", 5, 0, 0);
        Arbitro arbitro6 = new Arbitro("Jorge Figueroa Vazquez", 5000, "Española", 6, 0, 0);
        Arbitro arbitro7 = new Arbitro("Jesus Gil Manzano", 5000, "Española", 7, 0, 0);
        Arbitro arbitro8 = new Arbitro("Pablo Gonzalez Fuertes", 5000, "Española", 8, 0, 0);
        Arbitro arbitro9 = new Arbitro("Alejandro Herandez Hernandez", 5000, "Española", 9, 0, 0);
        Arbitro arbitro10 = new Arbitro("Javier Iglesias Villanueva", 5000, "Española", 10, 0, 0);
        Arbitro arbitro11 = new Arbitro("Juan Martinez Munuera", 5000, "Española", 11, 0, 0);
        Arbitro arbitro12 = new Arbitro("Antonio Mateu Lahoz", 5000, "Española", 12, 0, 0);
        Arbitro arbitro13 = new Arbitro("Mario Melero Lopez", 5000, "Española", 13, 0, 0);
        Arbitro arbitro14 = new Arbitro("Jose Luis Munuera Montero", 5000, "Española", 14, 0, 0);
        Arbitro arbitro15 = new Arbitro("Alejandro Muñiz Ruiz", 5000, "Española", 15, 0, 0);
        Arbitro arbitro16 = new Arbitro("Miguel Angel Ortiz Arias", 5000, "Española", 16, 0, 0);
        Arbitro arbitro17 = new Arbitro("Valentin Pizarro Gomez", 5000, "Española", 17, 0, 0);
        Arbitro arbitro18 = new Arbitro("Jose Maria Sanchez Martinez", 5000, "Española", 18, 0, 0);
        Arbitro arbitro19 = new Arbitro("Cesar Soto Grado", 5000, "Española", 19, 0, 0);
        Arbitro arbitro20 = new Arbitro("Guillermo Cuadra Fernandez", 5000, "Española", 20, 0, 0);
        Jornada jornada1a = new Jornada("1a", "FCB-BET", 12 / 8, 1 - 0, "ninguna", "Todo OK");
        Jornada jornada2a = new Jornada("2a", "FCB-SEV", 19 / 8, 2 - 0, "ninguna", "Todo OK");
        Jornada jornada3a = new Jornada("3a", "FCB-ESP", 26 / 8, 4 - 0, "ninguna", "Todo OK");
        Jornada jornada4a = new Jornada("4a", "FCB-RSC", 2 / 9, 1 - 0, "ninguna", "Todo OK");
        Jornada jornada5a = new Jornada("5a", "FCB-VAL", 9 / 9, 3 - 1, "ninguna", "Todo OK");
        Jornada jornada6a = new Jornada("6a", "FCB-VIL", 16 / 9, 5 - 2, "ninguna", "Todo OK");
        Jornada jornada7a = new Jornada("7a", "FCB-GET", 30 / 9, 3 - 0, "ninguna", "Todo OK");
        Jornada jornada8a = new Jornada("8a", "FCB-ATH", 7 / 10, 2 - 1, "ninguna", "Todo OK");
        Jornada jornada9a = new Jornada("9a", "FCB-ATL", 14 / 10, 1 - 1, "ninguna", "Todo OK");
        Jornada jornada10a = new Jornada("10a", "FCB-RMA", 18 / 10, 3 - 0, "ninguna", "Todo OK");
        Jornada jornada11a = new Jornada("11a", "FCB-OSA", 22 / 10, 1 - 0, "ninguna", "Todo OK");
        Jornada jornada12a = new Jornada("12a", "FCB-VAD", 28 / 10, 4 - 0, "ninguna", "Todo OK");
        Jornada jornada13a = new Jornada("13a", "FCB-ALM", 4 / 11, 2 - 1, "ninguna", "Todo OK");
        Jornada jornada14a = new Jornada("14a", "FCB-CAD", 8 / 11, 1 - 1, "ninguna", "Todo OK");
        Jornada jornada15a = new Jornada("15a", "FCB-RAY", 29 / 11, 2 - 0, "ninguna", "Todo OK");
        Jornada jornada16a = new Jornada("16a", "FCB-GIR", 6 / 1, 1 - 2, "ninguna", "Todo OK");
        Jornada jornada17a = new Jornada("17a", "FCB-MRC", 13 / 1, 2 - 1, "ninguna", "Todo OK");
        Jornada jornada18a = new Jornada("18a", "FCB-CLT", 20 / 1, 1 - 0, "ninguna", "Todo OK");
        Jornada jornada19a = new Jornada("19a", "FCB-ELC", 27 / 1, 3 - 0, "ninguna", "Todo OK");
        liga1.getEquipos().add(equipo1);
        liga1.getEquipos().add(equipo2);
        liga1.getEquipos().add(equipo3);
        liga1.getEquipos().add(equipo4);
        liga1.getEquipos().add(equipo5);
        liga1.getEquipos().add(equipo6);
        liga1.getEquipos().add(equipo7);
        liga1.getEquipos().add(equipo8);
        liga1.getEquipos().add(equipo9);
        liga1.getEquipos().add(equipo10);
        liga1.getEquipos().add(equipo11);
        liga1.getEquipos().add(equipo12);
        liga1.getEquipos().add(equipo13);
        liga1.getEquipos().add(equipo14);
        liga1.getEquipos().add(equipo15);
        liga1.getEquipos().add(equipo16);
        liga1.getEquipos().add(equipo17);
        liga1.getEquipos().add(equipo18);
        liga1.getEquipos().add(equipo19);
        liga1.getEquipos().add(equipo20);
        equipo1.getJugadores().add(portero1);
        equipo2.getJugadores().add(portero2);
        equipo3.getJugadores().add(portero3);
        equipo4.getJugadores().add(portero4);
        equipo5.getJugadores().add(portero5);
        equipo6.getJugadores().add(portero6);
        equipo7.getJugadores().add(portero7);
        equipo8.getJugadores().add(portero8);
        equipo9.getJugadores().add(portero9);
        equipo10.getJugadores().add(portero10);
        equipo11.getJugadores().add(portero11);
        equipo12.getJugadores().add(portero12);
        equipo13.getJugadores().add(portero13);
        equipo14.getJugadores().add(portero14);
        equipo15.getJugadores().add(portero15);
        equipo16.getJugadores().add(portero16);
        equipo17.getJugadores().add(portero17);
        equipo18.getJugadores().add(portero18);
        equipo19.getJugadores().add(portero19);
        equipo20.getJugadores().add(portero20);
        jornada1a.getArbitros().add(arbitro1);
        jornada2a.getArbitros().add(arbitro2);
        jornada3a.getArbitros().add(arbitro3);
        jornada4a.getArbitros().add(arbitro4);
        jornada5a.getArbitros().add(arbitro5);
        jornada6a.getArbitros().add(arbitro6);
        jornada7a.getArbitros().add(arbitro7);
        jornada8a.getArbitros().add(arbitro8);
        jornada9a.getArbitros().add(arbitro9);
        jornada10a.getArbitros().add(arbitro10);
        jornada11a.getArbitros().add(arbitro11);
        jornada12a.getArbitros().add(arbitro12);
        jornada13a.getArbitros().add(arbitro13);
        jornada14a.getArbitros().add(arbitro14);
        jornada15a.getArbitros().add(arbitro15);
        jornada16a.getArbitros().add(arbitro16);
        jornada17a.getArbitros().add(arbitro17);
        jornada18a.getArbitros().add(arbitro18);
        jornada19a.getArbitros().add(arbitro19);
        System.out.println(liga1);
        rfef.agregarliga("Liga Smartbank","España",1000000000);
        rfef.agregarliga("Primera RFEF", "España", 10000000);
        rfef.getLigas().get(0).agregarequipo();
        rfef.getLigas().get(0).agregarestadios();
        rfef.getLigas().get(0).agregarjornada();
        rfef.getLigas().get(0).agregararbitro();
        rfef.getLigas().get(1).agregarequipo();
        rfef.getLigas().get(1).agregarestadios();
        rfef.getLigas().get(1).agregararbitro();
        rfef.getLigas().get(1).agregarjornada();
        fifa.agregarliga("Premier League", "Inglaterra", 1000000000);
        fifa.getLigas().get(0).agregarequipo("Manchester City", "Etihad Stadium", 0, "Citycens");
        fifa.getLigas().get(0).agregarjornada("1a","MCY-MCU",12/8, 2-0,"Ninguna","Todo OK");
        fifa.getLigas().get(0).agregararbitro("",5000,"",100,0,0);
        fifa.getLigas().get(0).agregarestadios("Etihad Stadium",53400,"Manchester","Manchester City");
    }
}